services:
  app:
    build: . # build from Dockerfile
    command: >
      sh -c "sleep 15 &&
             npx sequelize-cli db:migrate &&
             npx sequelize-cli db:seed:all &&
             cd /app/
             npm run serve:dev"
    volumes:
      - "./:/app"
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./app.env
    depends_on:
      - db
  db:
    container_name: db-server
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    expose:
      - 3306

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - app

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: --auth --config /etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpw
      MONGO_INITDB_DATABASE: testdb
      TZ: Asia/Shanghai
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database/configdb:/data/configdb
      - ./database/data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports:
      - "27017:27017"
  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 127.0.0.1:8000:80
  #   environment:
  #     - PMA_HOST=db
  #   depends_on:
  #     - db
