services:
  app:
    build: . # build from Dockerfile
    command: >
      sh -c "sleep 5 &&
             npx sequelize-cli db:migrate &&
             npx sequelize-cli db:seed:all &&
             cd /app/
             npm run serve:dev"
    volumes:
      - "./:/app"
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./app.env
    depends_on:
      - db
  db:
    container_name: db-server
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    expose:
      - 3306

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - app

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 127.0.0.1:8000:80
  #   environment:
  #     - PMA_HOST=db
  #   depends_on:
  #     - db
