services:
  app:
    build: . # build from Dockerfile
    command: >
      sh -c "sleep 5 &&
             npx sequelize-cli db:migrate &&
             npx sequelize-cli db:seed:all &&
             cd /app/
             npm run serve:dev"
    volumes:
      - "./:/app"
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      SITE_DB_DATABASE: demo
      SITE_DB_USER: admin
      SITE_DB_PASSWORD: password
      SITE_DB_HOST: db
      JWT_KEY: 12345678
    depends_on:
      - db
  db:
    container_name: db-server
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db
